# SPDX-License-Identifier: GPL-2.0
# obj-y					+= heap-helpers.o
obj-$(CONFIG_DMABUF_HEAPS_DEFERRED_FREE) += deferred-free-helper.o
obj-$(CONFIG_DMABUF_HEAPS_PAGE_POOL)	+= page_pool.o
obj-$(CONFIG_DMABUF_HEAPS_SYSTEM)	+= rk_system_heap.o
obj-$(CONFIG_DMABUF_HEAPS_CMA)		+= rk_cma_heap.o
obj-$(CONFIG_DMABUF_HEAPS_SRAM)	+= sram_heap.o
# obj-$(CONFIG_DMABUF_HEAPS_SYSTEM)	+= system_heap.o
# obj-$(CONFIG_DMABUF_HEAPS_CMA)		+= cma_heap.o
